# Generated by Django 5.0.6 on 2024-06-07 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planting',
            name='planting_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.planttingtype', verbose_name='Tipo de plantio'),
        ),
    ]
